coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1% # allow minor coverage drops without failing
        branches:     # only run status checks for PRs
          - "!main"   # exclude the main branch from project coverage checks
    patch:
      default:
        target: 85%
        branches:
          - "!main"   # exclude main branch from patch checks

comment:
  require_changes: true
