site_name: pymmcore-plus
site_url: https://pymmcore-plus.github.io/pymmcore-plus
site_description: Pure python extensions of the C++ micro-manager core
# strict: true

repo_name: pymmcore-plus/pymmcore-plus
repo_url: https://github.com/pymmcore-plus/pymmcore-plus
edit_uri: edit/main/docs/
# use_directory_urls: false

watch:
  - src/pymmcore_plus
  - examples

nav:
  - index.md
  - install.md
  - Guides:
      - guides/events.md
      - guides/mda_engine.md
      - guides/custom_engine.md
      - guides/event_driven_acquisition.md
      - guides/logging.md
  - Examples:
      - examples/mda.md
      - examples/integration-with-qt.md
      - examples/context-set.md
      - examples/napari-micromanager.md
      - examples/following_changes_in_core.md
      - examples/pycro-manager-api.md
  # - API:
  #     - api/cmmcoreplus.md
  #     - api/mda.md
  #     - api/events.md
  #     - api/device.md
  #     - api/configuration.md
  #     - api/constants.md
  #     - Metadata: api/metadata.md
  #     - Utilities: api/utils.md
  - metadata.md
  - env_var.md
  - cli.md
  - troubleshooting.md
  - profiling.md
  - contributing.md

theme:
  name: "material"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.footer  # next/previous links in footer
  icon:
    logo: fontawesome/solid/microscope
    repo: fontawesome/brands/github
  favicon: images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

markdown_extensions:
  - tables
  - pymdownx.snippets # lets you include code snippets from other files
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - mkdocs-typer

hooks:
  - docs/_hooks.py

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - api-autonav:
      modules: [src/pymmcore_plus]
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pymmcore-plus.github.io/useq-schema/objects.inv
          options:
            preload_modules: [pymmcore]
            docstring_section_style: list # or "table"
            docstring_style: "numpy"
            heading_level: 2
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            # inherited_members: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true
            # allow_inspection: false # default is true
            # show_if_no_docstring: true # default is false
            show_source: false
extra_css:
  - stylesheets/extra.css
