# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.5.2.dev3+gf95b1c5.d20221117"
__version_tuple__ = version_tuple = (0, 5, 2, "dev3", "gf95b1c5.d20221117")
